export const fullGitaPage = String.raw`<!doctype html>
<html lang="en">
<head>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <meta name="theme-color" content="#090c12">
  <title>Full Bhagavad Gita · Mahabharat</title>
  <link rel="preconnect" href="https://fonts.googleapis.com">
  <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
  <link href="https://fonts.googleapis.com/css2?family=DM+Sans:wght@400;500;600;700&family=Manrope:wght@400;500;600;700;800&family=Noto+Serif+Bengali:wght@400;600;700&family=Noto+Serif+Devanagari:wght@400;600;700&display=swap" rel="stylesheet">
  <style>
    :root{color-scheme:dark;--bg:#090c12;--panel:#121823;--panel2:#18212e;--line:#2b3645;--ink:#edf1f7;--muted:#a6afbe;--gold:#f5b94f;--aqua:#7de0d0}
    *{box-sizing:border-box}html{scroll-behavior:smooth}body{margin:0;background:radial-gradient(circle at 77% -5%,#273d42 0,transparent 35%),radial-gradient(circle at 4% 15%,#251d23 0,transparent 30%),var(--bg);color:var(--ink);font-family:'DM Sans',sans-serif;min-height:100vh}
    button,select,input{font:inherit}button,a,select{touch-action:manipulation}button{cursor:pointer}a{color:inherit;text-decoration:none}button:focus-visible,a:focus-visible,select:focus-visible,input:focus-visible{outline:2px solid var(--aqua);outline-offset:3px}
    .shell{max-width:1600px;margin:auto;padding:0 30px}.topbar{height:80px;border-bottom:1px solid #ffffff16;display:flex;align-items:center;justify-content:space-between;gap:20px}.brand{font:800 16px 'Manrope',sans-serif;letter-spacing:.15em;text-transform:uppercase}.brand span{color:var(--gold)}.back{font-size:13px;color:var(--muted);border:1px solid var(--line);padding:10px 14px;border-radius:999px}.back:hover{color:var(--ink);border-color:var(--gold)}
    .masthead{min-height:465px;margin:34px 0 30px;border:1px solid #f5b94f35;border-radius:26px;position:relative;overflow:hidden;display:flex;align-items:center;background:#111823}.mast-art{position:absolute;right:0;top:0;width:60%;height:100%;object-fit:cover;object-position:60% center}.masthead:after{content:'';position:absolute;inset:0;background:linear-gradient(90deg,#090c12 0%,#0b0f17fa 39%,#0b0f1799 60%,#0b0f1700 88%);pointer-events:none}.mast-copy{position:relative;z-index:1;padding:46px 52px;max-width:760px}.eyebrow{font:800 11px 'Manrope',sans-serif;letter-spacing:.22em;text-transform:uppercase;color:var(--aqua)}h1,h2,h3,p{margin-top:0}h1{font:800 clamp(44px,6vw,88px)/.98 'Manrope',sans-serif;letter-spacing:-.075em;margin:14px 0 17px;max-width:650px}h1 em{font-style:normal;color:var(--gold)}.subline{color:#d6dce5;line-height:1.65;max-width:550px;font-size:15px}.edition{border:1px solid #f5b94f55;border-radius:18px;padding:12px 16px;color:var(--gold);font-size:12px;font-weight:700;background:#11141ccc;max-width:280px;line-height:1.5;margin-top:22px}
    .workbench{display:grid;grid-template-columns:290px minmax(0,1fr);gap:24px;padding-bottom:70px}.rail{border:1px solid var(--line);background:#111823db;border-radius:20px;padding:18px;height:max-content;position:sticky;top:20px}.rail-head{display:flex;align-items:center;justify-content:space-between;font:800 11px 'Manrope',sans-serif;letter-spacing:.18em;color:var(--muted);text-transform:uppercase;margin:4px 2px 15px}.chapter-list{display:grid;gap:5px;max-height:65vh;overflow:auto;padding-right:4px}.chapter-button{display:grid;grid-template-columns:30px 1fr;gap:9px;text-align:left;align-items:center;width:100%;border:1px solid transparent;border-radius:12px;color:#b9c1ce;background:transparent;padding:10px 8px}.chapter-button:hover{background:#ffffff09;color:var(--ink)}.chapter-button.active{border-color:#f5b94f75;background:#f5b94f13;color:var(--ink)}.chapter-number{font:800 13px 'Manrope',sans-serif;color:var(--gold)}.chapter-name{font-weight:700;font-size:12px}.chapter-count{display:block;color:var(--muted);font-weight:400;font-size:11px;margin-top:3px}.rail-foot{border-top:1px solid var(--line);margin-top:18px;padding:17px 5px 3px;font-size:12px;color:var(--muted);line-height:1.55}
    .main{min-width:0}.toolbar{display:flex;gap:10px;align-items:center;justify-content:space-between;margin-bottom:17px}.searchbox{display:flex;align-items:center;gap:9px;flex:1;max-width:600px;border:1px solid var(--line);background:var(--panel);border-radius:12px;padding:0 12px}.searchbox:focus-within{border-color:var(--aqua)}.searchbox input{border:0;background:transparent;color:var(--ink);padding:13px 0;outline:0;min-width:0;flex:1;font-size:13px}.searchbox input::placeholder{color:#84909f}.kbd{font-size:10px;color:var(--muted);border:1px solid var(--line);padding:3px 6px;border-radius:5px}.smallbutton,.action,.navbutton{border:1px solid var(--line);background:var(--panel);color:var(--ink);border-radius:10px;padding:10px 13px;font-size:12px;font-weight:700}.smallbutton:hover,.action:hover,.navbutton:hover{border-color:var(--gold)}.smallbutton:disabled,.navbutton:disabled{opacity:.4;cursor:not-allowed}
    .results{display:none;background:var(--panel);border:1px solid var(--line);border-radius:17px;margin-bottom:17px;padding:18px}.results.open{display:block}.result-head{display:flex;align-items:center;justify-content:space-between;color:var(--muted);font-size:12px;margin-bottom:8px}.result-list{display:grid;gap:6px;max-height:330px;overflow:auto}.result{border:1px solid var(--line);border-radius:10px;background:#ffffff05;color:var(--ink);padding:11px;text-align:left;width:100%}.result:hover{border-color:var(--aqua)}.result strong{color:var(--aqua);margin-right:8px}.result small{color:var(--muted);display:block;margin-top:5px;white-space:nowrap;overflow:hidden;text-overflow:ellipsis}
    .chapter-hero{border:1px solid var(--line);border-radius:24px;background:linear-gradient(130deg,#1b2730,#121721 56%,#24202a);padding:32px 36px;position:relative;overflow:hidden}.chapter-hero:after{content:'ॐ';position:absolute;right:32px;top:14px;color:#ffffff0b;font:170px 'Noto Serif Devanagari',serif;pointer-events:none}.chapter-kicker{color:var(--gold);font:800 11px 'Manrope',sans-serif;letter-spacing:.2em;text-transform:uppercase}.chapter-hero h2{font:800 clamp(25px,3vw,42px)/1.12 'Manrope',sans-serif;letter-spacing:-.045em;margin:12px 0 7px;position:relative;z-index:1}.chapter-sanskrit{font:600 20px 'Noto Serif Devanagari',serif;color:#e8d3aa;position:relative;z-index:1}.chapter-summary{font-size:13px;line-height:1.8;color:#c3cad5;max-width:780px;position:relative;z-index:1}.chapter-summary.collapsed{display:-webkit-box;-webkit-line-clamp:3;-webkit-box-orient:vertical;overflow:hidden}.textlink{border:0;background:none;color:var(--aqua);font-weight:700;padding:0;font-size:12px;position:relative;z-index:1}
    .reader{border:1px solid var(--line);border-radius:24px;background:#111721;margin-top:18px;padding:30px 36px}.reader-top{display:flex;align-items:center;justify-content:space-between;gap:12px;border-bottom:1px solid var(--line);padding-bottom:19px}.reference{font:800 13px 'Manrope',sans-serif;color:var(--gold);letter-spacing:.16em}.verse-nav{display:flex;gap:8px;align-items:center}.verse-nav select,.controls select{border:1px solid var(--line);background:var(--panel2);color:var(--ink);border-radius:9px;padding:9px 11px;font-size:12px;max-width:230px}.verse-nav select{min-width:95px}.sanskrit{white-space:pre-line;font:600 clamp(22px,3vw,34px)/1.9 'Noto Serif Devanagari',serif;color:#fff0cf;text-align:center;padding:30px 8px 18px}.transliteration{white-space:pre-line;text-align:center;font-size:14px;line-height:1.8;color:var(--aqua);font-style:italic;max-width:760px;margin:0 auto 25px}.controls{display:flex;align-items:end;gap:10px;flex-wrap:wrap;border-top:1px solid var(--line);padding-top:22px}.control{display:grid;gap:7px}.control label{font-size:10px;letter-spacing:.14em;text-transform:uppercase;color:var(--muted);font-weight:800}.translation{margin:20px 0 0;border-left:3px solid var(--gold);background:#f5b94f0a;border-radius:0 12px 12px 0;padding:20px 22px;line-height:1.75;font-size:17px}.translation.hindi{font-family:'Noto Serif Devanagari',serif}.attribution{font-size:11px;color:var(--gold);font-weight:800;margin:10px 0 0}.utility{display:flex;gap:8px;flex-wrap:wrap;margin-top:20px}.action.active{color:var(--gold);border-color:var(--gold)}details{border:1px solid var(--line);border-radius:14px;margin-top:17px;padding:17px 19px;background:#151d28}summary{cursor:pointer;font-size:13px;font-weight:800;color:var(--aqua)}details p{white-space:pre-line;color:#c5ccd7;font-size:13px;line-height:1.8;margin:15px 0 0}.compare{display:grid;gap:10px;margin-top:14px}.compare article{border-top:1px solid var(--line);padding-top:12px}.compare h4{margin:0 0 7px;color:var(--gold);font-size:12px}.compare p{margin:0;color:#c5ccd7;font-size:13px;line-height:1.7}.reader-bottom{display:flex;justify-content:space-between;gap:10px;margin-top:25px}.footer{border-top:1px solid var(--line);padding:25px 0 35px;color:var(--muted);font-size:12px;line-height:1.6}.footer a{color:var(--aqua);text-decoration:underline}.notice{font-size:11px;line-height:1.6;color:var(--muted);margin:14px 0 0}.loading{padding:30px;color:var(--muted)}
    .sanskrit.bangla-script,.translation.bangla{font-family:'Noto Serif Bengali',serif}.translation.bangla{line-height:1.95}.audio-panel{border:1px solid #7de0d044;border-radius:19px;background:linear-gradient(110deg,#142522,#151c28);padding:18px 22px;margin-bottom:17px}.audio-title{color:var(--aqua);font:800 11px 'Manrope',sans-serif;letter-spacing:.16em;text-transform:uppercase;margin-bottom:10px}.audio-row{display:flex;align-items:center;gap:10px;flex-wrap:wrap}.audio-row select{min-width:220px;max-width:100%;border:1px solid var(--line);background:var(--panel2);color:var(--ink);border-radius:9px;padding:10px;font-size:12px}.audio-row input{width:105px;accent-color:var(--gold)}.audio-credit,.audio-status{font-size:11px;color:var(--muted);line-height:1.55;margin:10px 0 0}.audio-credit a{color:var(--aqua);text-decoration:underline}.speech-status{font-size:11px;color:var(--muted);margin:10px 0 0}.study-note{font-size:12px;color:#c5ccd7;line-height:1.6;margin:12px 0 0}
    @media(max-width:900px){.workbench{grid-template-columns:1fr}.rail{position:static}.chapter-list{display:flex;overflow:auto;max-height:none}.chapter-button{min-width:185px}.masthead{min-height:390px}.mast-copy{max-width:610px}.rail-foot{display:none}}
    @media(max-width:600px){.shell{padding:0 16px}.topbar{height:67px}.brand{font-size:12px}.back{font-size:11px;padding:8px}.masthead{display:block;min-height:0;margin:20px 0 24px}.mast-art{position:relative;display:block;width:100%;height:auto;aspect-ratio:16/10;object-position:72% center}.masthead:after{display:none}.mast-copy{padding:24px 20px}.mast-copy h1{font-size:clamp(42px,12vw,64px)}.chapter-hero,.reader{padding:22px 18px}.reader-top{align-items:flex-start;flex-direction:column}.sanskrit{padding:22px 2px 12px}.toolbar{align-items:stretch}.kbd{display:none}.searchbox{max-width:none}.edition{font-size:11px;max-width:none}.translation{font-size:15px}.chapter-hero:after{font-size:110px}}
  </style>
</head>
<body>
  <div class="shell">
    <header class="topbar"><a href="/full-bhagavad-gita" class="brand">MAHABHARAT <span>/ FULL GITA</span></a><a class="back" href="/">← Back to Study Engine</a></header>
    <section class="masthead"><img class="mast-art" src="/assets/krishna-scholar-artist.webp" alt="Lord Krishna seated in a Vedic study, painting a luminous Hindu Goddess with a golden stylus" width="1672" height="941" fetchpriority="high"><div class="mast-copy"><div class="eyebrow">The text · The dialogue · The choice</div><h1>FULL BHAGAVAD <em>GITA.</em></h1><p class="subline">Read and listen verse by verse in Sanskrit, English, हिन्दी, and বাংলা, with attributed source translations and a clearly marked Bangla study meaning.</p><div class="edition">18 chapters · 701 numbered verse records<br><span style="color:#b4a591;font-weight:500">This source edition numbers chapter 13 through verse 35.</span></div></div></section>
    <div class="workbench">
      <aside class="rail" aria-label="Chapter navigation"><div class="rail-head"><span>Chapters</span><span>01—18</span></div><div id="chapter-list" class="chapter-list"><div class="loading">Loading chapters…</div></div><div class="rail-foot">A distinct source-based reader. Study progress in the main app uses a separate vocabulary dataset.</div></aside>
      <main class="main">
        <div class="toolbar"><form id="search-form" class="searchbox" role="search"><span aria-hidden="true">⌕</span><input id="search-input" type="search" placeholder="Search Sanskrit, meaning, translation, or 2.47" aria-label="Search the Gita" minlength="2" maxlength="100"><span class="kbd">ENTER</span></form><button id="bookmarks-button" class="smallbutton" type="button">☆ Saved</button></div>
        <section class="audio-panel" aria-label="Flute background music"><div class="audio-title">Krishna's flute · optional background music</div><div class="audio-row"><select id="music-track" aria-label="Choose flute music"><option value="folk1">Bansuri · folk melody I</option><option value="folk2">Bansuri · folk melody II</option><option value="bass">Bass bansuri · E</option><option value="bansuri">Bansuri · E melody</option><option value="carnatic">Carnatic flute · Mayamalavagowla</option></select><button id="music-play" class="action" type="button" aria-label="Play background audio">▶ Play</button><button id="music-mute" class="action" type="button" aria-label="Mute background audio">◖ Mute</button><label for="music-volume" class="notice">Volume</label><input id="music-volume" type="range" min="0" max="100" value="25" aria-label="Background volume"></div><p id="music-status" class="audio-status" role="status">Choose a flute track, then press Play. Music starts only when you ask.</p><p id="music-credit" class="audio-credit"></p><audio id="music-audio" preload="none" loop></audio></section>
        <section id="search-results" class="results" aria-live="polite"><div class="result-head"><span id="result-count"></span><button id="close-results" class="textlink" type="button">Close</button></div><div id="result-list" class="result-list"></div></section>
        <section id="chapter-hero" class="chapter-hero"><div class="loading">Loading source text…</div></section>
        <article id="reader" class="reader" aria-live="polite"></article>
        <p class="notice">Named English and Hindi translations are from the source edition. Bangla meanings are machine assisted from Swami Sivananda's English and have not been reviewed against Sanskrit; consult the source translations for close study. Numbering and interpretation can vary among editions.</p>
      </main>
    </div>
    <footer class="footer">Source: <a href="https://github.com/gita/bhagavad-gita-api" target="_blank" rel="noopener noreferrer">The Gita Initiative API</a> and its <a href="https://github.com/gita/gita" target="_blank" rel="noopener noreferrer">JSON corpus</a>. Translator names appear with each rendering.</footer>
  </div>
  <script>
  (function(){
    'use strict';
    const $ = (id) => document.getElementById(id);
    const el = (tag, className, content) => { const node = document.createElement(tag); if(className) node.className=className; if(content !== undefined) node.textContent=content; return node; };
    const state = { chapters:[], chapter:1, verse:1, data:null, language:'english', author:'Swami Sivananda', bookmarks:[], speech:null };
    try { state.bookmarks = JSON.parse(localStorage.getItem('fullGitaBookmarks') || '[]'); if(!Array.isArray(state.bookmarks)) state.bookmarks=[]; } catch(_) { state.bookmarks=[]; }
    try { state.language = ['english','hindi','bangla'].includes(localStorage.getItem('fullGitaLanguage')) ? localStorage.getItem('fullGitaLanguage') : 'english'; } catch(_) { /* optional storage */ }
    const music=$('music-audio');
    const tracks={
      folk1:{file:'bansuri-folk-melody-1.ogg',title:'Bansuri · folk melody I',credit:'MayankSingh33',source:'https://commons.wikimedia.org/wiki/File:Indian_Folk_Classical_Flute_Music_(1).wav',license:'CC BY-SA 4.0 · Ogg conversion'},
      folk2:{file:'bansuri-folk-melody-2.ogg',title:'Bansuri · folk melody II',credit:'MayankSingh33',source:'https://commons.wikimedia.org/wiki/File:Indian_Folk_Classical_Flute_Music_(2).wav',license:'CC BY-SA 4.0 · Ogg conversion'},
      bass:{file:'bansuri-bass-e.ogg',title:'Bass bansuri · E',credit:'Prithoo',source:'https://commons.wikimedia.org/wiki/File:Bansuri_sample_E_bass.ogg',license:'Public domain'},
      bansuri:{file:'bansuri-e.ogg',title:'Bansuri · E melody',credit:'Prithoo',source:'https://commons.wikimedia.org/wiki/File:Sample2.ogg',license:'Public domain'},
      carnatic:{file:'carnatic-flute.ogg',title:'Carnatic flute · Mayamalavagowla',credit:'Bansuri.arvind',source:'https://commons.wikimedia.org/wiki/File:Carnatic_flute.ogg',license:'CC BY-SA 3.0'}
    };
    function updateMusic(){const playing=!music.paused;$('music-play').textContent=playing?'Ⅱ Pause':'▶ Play';$('music-play').setAttribute('aria-label',playing?'Pause background audio':'Play background audio');$('music-mute').textContent=music.muted?'◖ Unmute':'◖ Mute';$('music-mute').setAttribute('aria-label',music.muted?'Unmute background audio':'Mute background audio');}
    function chooseTrack(key){const track=tracks[key]||tracks.folk1,wasPlaying=!music.paused;music.src='/full-gita/audio/'+track.file;music.load();const credit=$('music-credit');credit.replaceChildren(document.createTextNode(track.title+' · '+track.credit+' · '+track.license+' · '));const link=el('a','','Source and license');link.href=track.source;link.target='_blank';link.rel='noopener noreferrer';credit.append(link);$('music-status').textContent='Selected '+track.title+'.';try{localStorage.setItem('fullGitaTrack',key);}catch(_){}if(wasPlaying)music.play().catch(()=>{$('music-status').textContent='Playback was blocked. Press Play to start.';});updateMusic();}
    try{const saved=localStorage.getItem('fullGitaTrack');if(tracks[saved])$('music-track').value=saved;music.muted=localStorage.getItem('fullGitaMuted')==='true';const volume=Number(localStorage.getItem('fullGitaFluteVolume'));if(Number.isFinite(volume)&&volume>=0&&volume<=100&&localStorage.getItem('fullGitaFluteVolume')!==null)$('music-volume').value=String(volume);}catch(_){}
    music.volume=Number($('music-volume').value)/100;chooseTrack($('music-track').value);$('music-track').addEventListener('change',()=>chooseTrack($('music-track').value));$('music-play').addEventListener('click',async()=>{if(music.paused){try{await music.play();$('music-status').textContent='Playing '+tracks[$('music-track').value].title+'.';}catch(_){$('music-status').textContent='Audio could not start. Try again or choose another track.';}}else{music.pause();$('music-status').textContent='Background audio paused.';}updateMusic();});$('music-mute').addEventListener('click',()=>{music.muted=!music.muted;try{localStorage.setItem('fullGitaMuted',String(music.muted));}catch(_){}updateMusic();});$('music-volume').addEventListener('input',()=>{music.volume=Number($('music-volume').value)/100;try{localStorage.setItem('fullGitaFluteVolume',$('music-volume').value);}catch(_){}});music.addEventListener('error',()=>{$('music-status').textContent='This track could not be loaded.';updateMusic();});music.addEventListener('play',updateMusic);music.addEventListener('pause',updateMusic);
    const toBanglaScript=(text)=>text.replace(/ॐ/g,'ওঁ').replace(/व/g,'ব').replace(/[\u0900-\u0963\u0966-\u096f]/gu,(letter)=>String.fromCodePoint(letter.codePointAt(0)+128)).replace(/[0-9]/g,(digit)=>String.fromCodePoint(0x09E6+Number(digit)));
    function stopSpeech(resumeMusic=true){if('speechSynthesis' in window)speechSynthesis.cancel();if(state.speechButton)state.speechButton.textContent=state.speechButton.dataset.label;const resume=state.speechMusicWasPlaying;state.speech=null;state.speechButton=null;state.speechMusicWasPlaying=false;const status=$('speech-status');if(status)status.textContent='';if(resume&&resumeMusic)music.play().catch(()=>{});}
    function speak(text,lang,button){if(!('speechSynthesis' in window)){button.textContent='Speech unavailable';return;}if(state.speech&&state.speechButton===button){stopSpeech();return;}const wasPlaying=state.speechMusicWasPlaying||!music.paused;stopSpeech(false);const voices=speechSynthesis.getVoices();const voice=voices.find((entry)=>entry.lang.toLowerCase()===lang.toLowerCase())||voices.find((entry)=>entry.lang.toLowerCase().startsWith(lang.slice(0,2).toLowerCase()));if(lang.startsWith('bn')&&!voice){$('speech-status').textContent='A Bangla voice is not installed in this browser. Add a Bangla system voice to listen.';if(wasPlaying)music.play().catch(()=>{});return;}if(wasPlaying)music.pause();const utterance=new SpeechSynthesisUtterance(text);utterance.lang=lang;if(voice)utterance.voice=voice;utterance.rate=lang.startsWith('bn') ? .82 : .88;state.speech=utterance;state.speechButton=button;state.speechMusicWasPlaying=wasPlaying;button.textContent='■ Stop listening';$('speech-status').textContent='Speaking with your browser voice.';const finish=()=>{if(state.speech!==utterance)return;state.speech=null;state.speechButton=null;state.speechMusicWasPlaying=false;button.textContent=button.dataset.label;$('speech-status').textContent='';if(wasPlaying)music.play().catch(()=>{});};utterance.onend=finish;utterance.onerror=finish;speechSynthesis.speak(utterance);}
    const ref = (item) => item.chapter + '.' + item.verse;
    const formatError = (message) => { $('reader').replaceChildren(el('p','loading',message)); };
    const fetchJson = async (url) => { const response=await fetch(url); const data=await response.json(); if(!response.ok) throw new Error(data.error || 'Request failed'); return data; };
    function renderChapters(){
      const list=$('chapter-list'); list.replaceChildren();
      state.chapters.forEach((chapter) => { const button=el('button','chapter-button'); button.type='button'; button.setAttribute('aria-label','Chapter '+chapter.number+': '+chapter.englishName); if(chapter.number===state.chapter) button.classList.add('active');
        button.append(el('span','chapter-number',String(chapter.number).padStart(2,'0'))); const name=el('span','chapter-name',chapter.englishName); name.append(el('small','chapter-count',chapter.verseCount+' verses')); button.append(name); button.addEventListener('click',()=>openReference(chapter.number,1)); list.append(button); });
    }
    function renderChapter(){
      const chapter=state.data.chapter, hero=$('chapter-hero'); hero.replaceChildren();
      hero.append(el('div','chapter-kicker','Chapter '+String(chapter.number).padStart(2,'0')+' / '+chapter.verseCount+' verses'));
      hero.append(el('h2','',chapter.englishName)); hero.append(el('div','chapter-sanskrit',chapter.name));
      const summary=el('p','chapter-summary collapsed',chapter.summaryEnglish); hero.append(summary);
      const more=el('button','textlink','Read chapter context +'); more.type='button'; more.addEventListener('click',()=>{ const expanded=!summary.classList.toggle('collapsed'); more.textContent=expanded?'Show less −':'Read chapter context +'; }); hero.append(more);
    }
    function activeVerse(){ return state.data?.verses.find((item)=>item.verse===state.verse); }
    function renderReader(){
      const item=activeVerse(); if(!item){formatError('Verse unavailable in this edition.');return;}
      const reader=$('reader'); reader.replaceChildren(); const top=el('div','reader-top'); top.append(el('div','reference','VERSE '+ref(item)));
      const nav=el('div','verse-nav'); const select=el('select'); select.setAttribute('aria-label','Choose verse'); state.data.verses.forEach((verse)=>{const option=el('option','',String(verse.verse).padStart(2,'0')+' / '+state.data.chapter.verseCount); option.value=String(verse.verse); select.append(option);}); select.value=String(item.verse); select.addEventListener('change',()=>openReference(state.chapter,Number(select.value))); nav.append(select); top.append(nav); reader.append(top);
      const script=el('div','sanskrit'+(state.language==='bangla'?' bangla-script':''),state.language==='bangla'?toBanglaScript(item.sanskrit):item.sanskrit);script.lang=state.language==='bangla'?'bn':'sa';reader.append(script); reader.append(el('p','transliteration',item.transliteration));
      const controls=el('div','controls'); const langWrap=el('div','control'), langLabel=el('label','', 'Language'), langSelect=el('select'); langLabel.htmlFor='gita-language'; langSelect.id='gita-language'; [['english','English'],['hindi','हिन्दी'],['bangla','বাংলা']].forEach(([value,label])=>{const option=el('option','',label);option.value=value;langSelect.append(option);}); langSelect.value=state.language; langSelect.addEventListener('change',()=>{stopSpeech();state.language=langSelect.value;state.author=state.language==='hindi'?'Swami Ramsukhdas':'Swami Sivananda';try{localStorage.setItem('fullGitaLanguage',state.language);}catch(_){}renderReader();}); langWrap.append(langLabel,langSelect); controls.append(langWrap);
      const authorWrap=el('div','control'), authorLabel=el('label','',state.language==='bangla'?'Bangla edition':'Translation by'), authorSelect=el('select'); authorLabel.htmlFor='gita-author'; authorSelect.id='gita-author'; const available=item.translations.filter((translation)=>translation.language===state.language);if(state.language==='bangla'){const option=el('option','','Study meaning · machine assisted');option.value='bangla';authorSelect.append(option);authorSelect.disabled=true;}else{available.forEach((translation)=>{const option=el('option','',translation.author);option.value=translation.author;authorSelect.append(option);}); if(!available.some((translation)=>translation.author===state.author))state.author=available[0]?.author||''; authorSelect.value=state.author; authorSelect.addEventListener('change',()=>{state.author=authorSelect.value;renderReader();});} authorWrap.append(authorLabel,authorSelect); controls.append(authorWrap); reader.append(controls);
      const translation=available.find((entry)=>entry.author===state.author);const meaning=state.language==='bangla'?item.bangla:(translation?.text||'No translation available.');const block=el('blockquote','translation'+(state.language==='hindi'?' hindi':state.language==='bangla'?' bangla':''),meaning||'Bangla meaning unavailable.');if(state.language==='bangla')block.lang='bn';reader.append(block); reader.append(el('p','attribution',state.language==='bangla'?'Bangla study meaning · machine assisted from Swami Sivananda’s English':state.author+' · '+(state.language==='hindi'?'Hindi':'English')+' translation'));if(state.language==='bangla')reader.append(el('p','study-note','This Bangla rendering is for access and listening, not a scholarly translation. Compare the Sanskrit and named translations below for precision.'));
      const utility=el('div','utility'); const saved=state.bookmarks.includes(ref(item)); const bookmark=el('button','action'+(saved?' active':''),saved?'★ Saved':'☆ Save verse');bookmark.type='button';bookmark.addEventListener('click',()=>{const key=ref(item);state.bookmarks=state.bookmarks.includes(key)?state.bookmarks.filter((value)=>value!==key):[...state.bookmarks,key];localStorage.setItem('fullGitaBookmarks',JSON.stringify(state.bookmarks));renderReader();});utility.append(bookmark);
      const copy=el('button','action','↗ Copy link');copy.type='button';copy.addEventListener('click',async()=>{try{await navigator.clipboard.writeText(location.href);copy.textContent='Copied';}catch(_){copy.textContent='Use the address bar to copy';}});utility.append(copy);
      const listen=el('button','action',state.language==='bangla'?'▶ Hear verse · বাংলা':'▶ Hear Sanskrit');listen.type='button';listen.dataset.label=listen.textContent;listen.addEventListener('click',()=>speak(state.language==='bangla'?toBanglaScript(item.sanskrit):item.sanskrit,state.language==='bangla'?'bn-BD':'hi-IN',listen));utility.append(listen);
      const hearMeaning=el('button','action',state.language==='bangla'?'▶ Hear meaning · বাংলা':state.language==='hindi'?'▶ Hear meaning · हिन्दी':'▶ Hear meaning · English');hearMeaning.type='button';hearMeaning.dataset.label=hearMeaning.textContent;hearMeaning.addEventListener('click',()=>speak(meaning,state.language==='bangla'?'bn-BD':state.language==='hindi'?'hi-IN':'en-US',hearMeaning));utility.append(hearMeaning);reader.append(utility);reader.append(el('p','speech-status',''));
      const meanings=el('details');meanings.append(el('summary','','Word meanings · source glossary'));meanings.append(el('p','',item.wordMeanings));reader.append(meanings);
      const compare=el('details');compare.append(el('summary','','Compare all seven attributed source translations')); const compareList=el('div','compare');item.translations.forEach((entry)=>{const article=el('article');article.append(el('h4','',entry.author+' · '+entry.language));article.append(el('p','',entry.text));compareList.append(article);});compare.append(compareList);reader.append(compare);
      const bottom=el('div','reader-bottom');const prev=el('button','navbutton','← Previous');prev.type='button';prev.disabled=item.chapter===1&&item.verse===1;prev.addEventListener('click',()=>step(-1));const next=el('button','navbutton','Next →');next.type='button';next.disabled=item.chapter===18&&item.verse===state.data.chapter.verseCount;next.addEventListener('click',()=>step(1));bottom.append(prev,next);reader.append(bottom);
    }
    async function openReference(chapter,verse){
      if(chapter<1||chapter>18)return; stopSpeech();try{if(!state.data||state.chapter!==chapter){$('reader').replaceChildren(el('p','loading','Opening chapter…'));state.data=await fetchJson('/api/full-gita/chapters/'+chapter);} const max=state.data.chapter.verseCount;state.chapter=chapter;state.verse=Math.max(1,Math.min(max,verse));history.replaceState(null,'','#'+state.chapter+'.'+state.verse);renderChapters();renderChapter();renderReader();}catch(error){formatError(error.message);}
    }
    function step(delta){let chapter=state.chapter,verse=state.verse+delta;if(verse<1){chapter--;verse=state.chapters[chapter-1]?.verseCount||1;}else if(verse>state.data.chapter.verseCount){chapter++;verse=1;}openReference(chapter,verse);}
    function renderResults(results,title){const box=$('search-results'),list=$('result-list');list.replaceChildren();$('result-count').textContent=title;results.forEach((item)=>{const button=el('button','result');button.type='button';const label=el('strong','',item.chapter+'.'+item.verse);button.append(label,document.createTextNode(item.transliteration.replace(/\s+/g,' ').slice(0,95)));button.append(el('small','',item.preview||item.sanskrit.replace(/\s+/g,' ').slice(0,110)));button.addEventListener('click',()=>{box.classList.remove('open');openReference(item.chapter,item.verse);});list.append(button);});if(!results.length)list.append(el('p','notice','No verses found. Try another term.'));box.classList.add('open');}
    $('search-form').addEventListener('submit',async(event)=>{event.preventDefault();const q=$('search-input').value.trim();if(q.length<2)return;try{const data=await fetchJson('/api/full-gita/search?q='+encodeURIComponent(q));renderResults(data.results,data.total+' matches · first 60 shown');}catch(error){renderResults([],error.message);}});
    $('bookmarks-button').addEventListener('click',()=>{const results=state.bookmarks.map((key)=>{const [chapter,verse]=key.split('.').map(Number);const item=(chapter===state.chapter?state.data?.verses.find((row)=>row.verse===verse):null);return{chapter,verse,transliteration:item?.transliteration||'Saved verse',sanskrit:item?.sanskrit||'',preview:''};});renderResults(results,results.length+' saved verses on this device');});
    $('close-results').addEventListener('click',()=>$('search-results').classList.remove('open'));
    window.addEventListener('hashchange',()=>{const match=location.hash.match(/^#(\d+)\.(\d+)$/);if(match)openReference(Number(match[1]),Number(match[2]));});
    async function start(){try{state.chapters=await fetchJson('/api/full-gita/chapters');const match=location.hash.match(/^#(\d+)\.(\d+)$/);await openReference(match?Number(match[1]):1,match?Number(match[2]):1);}catch(error){formatError(error.message);}}
    start();
  })();
  </script>
</body>
</html>`;
